jsm:
  services:
    - root: java-projects/fat-jar
      name: service1
      java_home: /usr/lib/jvm/java-11-openjdk
      jvm_args: -Xmx1g
      app_args: "--server.port=8282 --spring.profiles.active=test"
      log_root: ${root}/logs
      terminate_timeout: 10   # 服务正常结束所需最多时间，如果超过这个时间进程依然没有结束，则强制结束进程
    - root: java-projects/lib-dir
      name: service2
      java_home: /usr/lib/jvm/java-17-openjdk
    - root: /home/java/service3
      name: service3
      java_home: /usr/lib/jvm/java-11-openjdk
      log_root: /other/log/path
    - root: /home/java/service4
      name: service4
      executable: my_java_executable   # executable can be alias command for java
    - root: /home/java/service5
      name: service5
    - root: /home/java/service6
      name: service6
    - root: /home/java/service7
      name: service7
    - root: /home/java/service8
      name: service8
    - root: /home/java/service9
      name: service9
    - root: /home/java/service10
      name: service10
    - root: /home/java/service11
      name: service11
    - root: /home/java/service12
      name: service12
    - root: /home/java/service13
      name: service13